-- =============================
-- Drop all tables (child → parent order)
-- =============================

-- Child tables
DROP TABLE photo CASCADE CONSTRAINTS;
DROP TABLE task_progress CASCADE CONSTRAINTS;
DROP TABLE decorator_choice CASCADE CONSTRAINTS;
DROP TABLE construction_task CASCADE CONSTRAINTS;
DROP TABLE housetask CASCADE CONSTRAINTS;
DROP TABLE rooms CASCADE CONSTRAINTS;
DROP TABLE option_stage_price CASCADE CONSTRAINTS;
DROP TABLE "Option" CASCADE CONSTRAINTS;
DROP TABLE optioncategory CASCADE CONSTRAINTS;
DROP TABLE decorator_session CASCADE CONSTRAINTS;
DROP TABLE sale CASCADE CONSTRAINTS;

-- Mid-level
DROP TABLE house CASCADE CONSTRAINTS;
DROP TABLE lot CASCADE CONSTRAINTS;
DROP TABLE elevation CASCADE CONSTRAINTS;

-- Independent entities
DROP TABLE buyer CASCADE CONSTRAINTS;
DROP TABLE employee CASCADE CONSTRAINTS;
DROP TABLE bank_worker CASCADE CONSTRAINTS;
DROP TABLE bank CASCADE CONSTRAINTS;
DROP TABLE escrowagent CASCADE CONSTRAINTS;
DROP TABLE housestyle CASCADE CONSTRAINTS;
DROP TABLE subdivision CASCADE CONSTRAINTS;
DROP TABLE school CASCADE CONSTRAINTS;

-- Done
