-- Drop existing tables (this is fine if some fail with "does not exist")
DROP TABLE sale CASCADE CONSTRAINTS;
DROP TABLE decorator_choice CASCADE CONSTRAINTS;
DROP TABLE decorator_session CASCADE CONSTRAINTS;
DROP TABLE task_progress CASCADE CONSTRAINTS;
DROP TABLE housetask CASCADE CONSTRAINTS;
DROP TABLE house CASCADE CONSTRAINTS;
DROP TABLE elevation CASCADE CONSTRAINTS;
DROP TABLE housestyle CASCADE CONSTRAINTS;
DROP TABLE buyer CASCADE CONSTRAINTS;
DROP TABLE employee CASCADE CONSTRAINTS;
DROP TABLE construction_task CASCADE CONSTRAINTS;
DROP TABLE lot CASCADE CONSTRAINTS;
DROP TABLE subdivision CASCADE CONSTRAINTS;
DROP TABLE escrowagent CASCADE CONSTRAINTS;
DROP TABLE option_stage_price CASCADE CONSTRAINTS;
DROP TABLE "Option" CASCADE CONSTRAINTS;
DROP TABLE optioncategory CASCADE CONSTRAINTS;


-- Generated by Oracle SQL Developer Data Modeler 18.3.0.268.1156
--   at:        2025-09-26 17:23:32 EDT
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



CREATE TABLE buyer (
    buyer_id   NUMBER NOT NULL,
    name       VARCHAR2(250),
    address    LONG,
    city       VARCHAR2(50),
    state      VARCHAR2(2),
    zip        VARCHAR2(10),
    phone      VARCHAR2(15),
    email      VARCHAR2(100)
);

ALTER TABLE buyer ADD CONSTRAINT buyer_pk PRIMARY KEY ( buyer_id );

CREATE TABLE construction_task (
    task_id       NUMBER NOT NULL,
    description   VARCHAR2(1000),
    stage         NUMBER,
    basecost      NUMBER(12, 2),
    approval      CHAR(1)
);

ALTER TABLE construction_task ADD CONSTRAINT construction_task_pk PRIMARY KEY ( task_id );

CREATE TABLE decorator_choice (
    decoratorchoice_id    NUMBER NOT NULL,
    room                  VARCHAR2(250),
    item                  VARCHAR2(250),
    description           VARCHAR2(1000),
    price                 NUMBER(12, 2),
    decoratorsession_id   NUMBER NOT NULL,
    option_option_id      NUMBER NOT NULL
);

ALTER TABLE decorator_choice ADD CONSTRAINT decorator_choice_pk PRIMARY KEY ( decoratorchoice_id );

CREATE TABLE decorator_session (
    decoratorsession_id      NUMBER NOT NULL,
    "Date"                   DATE,
    stage                    NUMBER,
    housetask_housetask_id   NUMBER NOT NULL,
    approval                 CHAR(1)
);

ALTER TABLE decorator_session ADD CONSTRAINT decorator_session_pk PRIMARY KEY ( decoratorsession_id );

CREATE TABLE elevation (
    elevation_id           NUMBER NOT NULL,
    elevationcode          VARCHAR2(250),
    description            VARCHAR2(1000),
    additionalcostsketch   VARCHAR2(1000),
    housestyle_style_id    NUMBER NOT NULL
);

ALTER TABLE elevation ADD CONSTRAINT elevation_pk PRIMARY KEY ( elevation_id );

CREATE TABLE employee (
    employee_id   NUMBER NOT NULL,
    name          VARCHAR2(250),
    title         VARCHAR2(1000),
    email         VARCHAR2(100),
    phone         VARCHAR2(15),
    active        CHAR(1),
    hire_date     DATE
);

ALTER TABLE employee ADD CONSTRAINT employee_pk PRIMARY KEY ( employee_id );

CREATE TABLE escrowagent (
    escrowagent_id   NUMBER NOT NULL,
    name             VARCHAR2(250),
    address          LONG,
    city             VARCHAR2(50),
    state            VARCHAR2(2),
    zip              VARCHAR2(10)
);

ALTER TABLE escrowagent ADD CONSTRAINT escrowagent_pk PRIMARY KEY ( escrowagent_id );

CREATE TABLE house (
    house_id                   NUMBER NOT NULL,
    currentconstructionstage   NUMBER,
    estimatedcompletion        DATE,
    lot_lot_id                 NUMBER NOT NULL,
    housestyle_style_id        NUMBER NOT NULL,
    elevation_elevation_id     NUMBER NOT NULL
);

ALTER TABLE house ADD CONSTRAINT house_pk PRIMARY KEY ( house_id );

CREATE TABLE housestyle (
    style_id           NUMBER NOT NULL,
    stylename          VARCHAR2(250),
    baseprice          NUMBER(12, 2),
    styledescription   VARCHAR2(1000),
    "Size"             NUMBER,
    photo              BLOB,
    nowindows          NUMBER,
    ceiling            VARCHAR2(1000)
);

ALTER TABLE housestyle ADD CONSTRAINT housestyle_pk PRIMARY KEY ( style_id );

CREATE TABLE housetask (
    housetask_id                NUMBER NOT NULL,
    stage                       NUMBER,
    required                    CHAR(1),
    plannedstart                DATE,
    plannedend                  DATE,
    notes                       VARCHAR2(1000),
    house_house_id              NUMBER NOT NULL,
    employee_employee_id        NUMBER NOT NULL,
    construction_task_task_id   NUMBER NOT NULL,
    plannedcost                 NUMBER(12, 2),
    actualcost                  NUMBER(12, 2)
);

ALTER TABLE housetask ADD CONSTRAINT housetask_pk PRIMARY KEY ( housetask_id );

CREATE TABLE lot (
    lot_id                       NUMBER NOT NULL,
    address                      LONG,
    city                         VARCHAR2(50),
    state                        VARCHAR2(2),
    zip                          VARCHAR2(10),
    lotsize                      NUMBER,
    description                  VARCHAR2(1000),
    lotpremium                   NUMBER(12, 2),
    subdivision_subdivision_id   NUMBER NOT NULL
);

ALTER TABLE lot ADD CONSTRAINT lot_pk PRIMARY KEY ( lot_id );

CREATE TABLE "Option" (
    option_id                    NUMBER NOT NULL,
    option_code                  VARCHAR2(250),
    description                  VARCHAR2(1000),
    optioncategory_category_id   NUMBER NOT NULL
);

ALTER TABLE "Option" ADD CONSTRAINT option_pk PRIMARY KEY ( option_id );

CREATE TABLE option_stage_price (
    cost               NUMBER(12, 2),
    revision_date      DATE,
    stage              NUMBER,
    option_option_id   NUMBER NOT NULL
);

CREATE TABLE optioncategory (
    category_id    NUMBER NOT NULL,
    categoryname   VARCHAR2(250)
);

ALTER TABLE optioncategory ADD CONSTRAINT optioncategory_pk PRIMARY KEY ( category_id );

CREATE TABLE sale (
    sale_id                      NUMBER NOT NULL,
    "Date"                       DATE,
    baseprice                    NUMBER(12, 2),
    financing_method             VARCHAR2(1000),
    escrowdeposit                NUMBER(12, 2),
    estimatedcompletion          DATE,
    receivedsubdivision          CHAR(1),
    receiveddisclosureform       CHAR(1),
    receivedcontractcopy         CHAR(1),
    house_house_id               NUMBER NOT NULL,
    buyer_buyer_id               NUMBER NOT NULL,
    escrowagent_escrowagent_id   NUMBER NOT NULL,
    employee_employee_id         NUMBER NOT NULL
);

CREATE UNIQUE INDEX sale__idx ON
    sale (
        house_house_id
    ASC );

ALTER TABLE sale ADD CONSTRAINT sale_pk PRIMARY KEY ( sale_id );

CREATE TABLE subdivision (
    subdivision_id   NUMBER NOT NULL,
    name             VARCHAR2(50),
    city             VARCHAR2(50),
    state            VARCHAR2(2),
    zip              VARCHAR2(10)
);

ALTER TABLE subdivision ADD CONSTRAINT subdivision_pk PRIMARY KEY ( subdivision_id );

CREATE TABLE task_progress (
    progress_id              NUMBER NOT NULL,
    "Date"                   DATE,
    percent_complete         NUMBER(3, 2),
    estimatedcompletion      DATE,
    photo                    BLOB,
    stage                    NUMBER,
    housetask_housetask_id   NUMBER NOT NULL
);

ALTER TABLE task_progress ADD CONSTRAINT task_progress_pk PRIMARY KEY ( progress_id );

ALTER TABLE decorator_choice
    ADD CONSTRAINT decorator_choice_option_fk FOREIGN KEY ( option_option_id )
        REFERENCES "Option" ( option_id );

ALTER TABLE decorator_choice
    ADD CONSTRAINT decorator_session_fk FOREIGN KEY ( decoratorsession_id )
        REFERENCES decorator_session ( decoratorsession_id );

ALTER TABLE decorator_session
    ADD CONSTRAINT decorator_session_housetask_fk FOREIGN KEY ( housetask_housetask_id )
        REFERENCES housetask ( housetask_id );

ALTER TABLE elevation
    ADD CONSTRAINT elevation_housestyle_fk FOREIGN KEY ( housestyle_style_id )
        REFERENCES housestyle ( style_id );

ALTER TABLE house
    ADD CONSTRAINT house_elevation_fk FOREIGN KEY ( elevation_elevation_id )
        REFERENCES elevation ( elevation_id );

ALTER TABLE house
    ADD CONSTRAINT house_housestyle_fk FOREIGN KEY ( housestyle_style_id )
        REFERENCES housestyle ( style_id );

ALTER TABLE house
    ADD CONSTRAINT house_lot_fk FOREIGN KEY ( lot_lot_id )
        REFERENCES lot ( lot_id );

ALTER TABLE housetask
    ADD CONSTRAINT housetask_construction_task_fk FOREIGN KEY ( construction_task_task_id )
        REFERENCES construction_task ( task_id );

ALTER TABLE housetask
    ADD CONSTRAINT housetask_employee_fk FOREIGN KEY ( employee_employee_id )
        REFERENCES employee ( employee_id );

ALTER TABLE housetask
    ADD CONSTRAINT housetask_house_fk FOREIGN KEY ( house_house_id )
        REFERENCES house ( house_id );

ALTER TABLE lot
    ADD CONSTRAINT lot_subdivision_fk FOREIGN KEY ( subdivision_subdivision_id )
        REFERENCES subdivision ( subdivision_id );

ALTER TABLE option_stage_price
    ADD CONSTRAINT option_stage_price_option_fk FOREIGN KEY ( option_option_id )
        REFERENCES "Option" ( option_id );

ALTER TABLE "Option"
    ADD CONSTRAINT optioncategory_fk FOREIGN KEY ( optioncategory_category_id )
        REFERENCES optioncategory ( category_id );

ALTER TABLE sale
    ADD CONSTRAINT sale_buyer_fk FOREIGN KEY ( buyer_buyer_id )
        REFERENCES buyer ( buyer_id );

ALTER TABLE sale
    ADD CONSTRAINT sale_employee_fk FOREIGN KEY ( employee_employee_id )
        REFERENCES employee ( employee_id );

ALTER TABLE sale
    ADD CONSTRAINT sale_escrowagent_fk FOREIGN KEY ( escrowagent_escrowagent_id )
        REFERENCES escrowagent ( escrowagent_id );

ALTER TABLE sale
    ADD CONSTRAINT sale_house_fk FOREIGN KEY ( house_house_id )
        REFERENCES house ( house_id );

ALTER TABLE task_progress
    ADD CONSTRAINT task_progress_housetask_fk FOREIGN KEY ( housetask_housetask_id )
        REFERENCES housetask ( housetask_id );


-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            17
-- CREATE INDEX                             1
-- ALTER TABLE                             52
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0